version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
    # START_HIGHLIGHT
    env_file:
      - .env/development/database
      - .env/development/web
    # END_HIGHLIGHT

  redis:
    image: redis

  database:
    image: postgres
    # START_HIGHLIGHT
    env_file:
      - .env/development/database
    # END_HIGHLIGHT
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: